### ISSUE TITLE
Documentation: Community guidelines missing

### ISSUE THREAD

**Issue by rspirgel** [montilab/nf-gwas-pipeline#2]
Did not see mention in the documentation or paper of how users could: 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support 

https://github.com/openjournals/joss-reviews/issues/2957

**Comment by anfederico** [comment]
I've added a contributing document to the repository which describes guidelines for users to adhere to as well as channels (Github Issues) to report issues/seek help. We will refer to this document in the paper.
