### ISSUE TITLE
cannot run test

### ISSUE THREAD

**Issue by PavitaKae** [montilab/nf-gwas-pipeline#5]
Dear all,
I follow your installation, it's look good but I cannot run test. 
./nextflow gwas.nf -c gwas.config -with-docker montilab/gwas

I run on Mac environment

G W A S  ~  P I P E L I N E

================================
outdir    : /Users/pavita/nf-gwas-pipeline/results

vcf       : /Users/pavita/nf-gwas-pipeline/data/toy_vcf.csv
pheno     : /Users/pavita/nf-gwas-pipeline/data/pheno_file_logistic.csv
snpset    : /Users/pavita/nf-gwas-pipeline/data/snpset.txt

phenotype : outcome
covars    : age,sex,PC1,PC2,PC3,PC4
model     : logistic
test      : Score
ref       : hg19

-

executor >  local (78)
[6c/577702] process > qc_miss (chr_22)          [100%] 22 of 22 ✔
executor >  local (78)
[6c/577702] process > qc_miss (chr_22)          [100%] 22 of 22 ✔
[93/c59706] process > qc_mono (chr_22)          [100%] 22 of 22 ✔
[1c/6fd96e] process > vcf_to_gds (chr_22)       [100%] 22 of 22 ✔
[16/1dd261] process > merge_gds                 [100%] 1 of 1 ✔
[c0/c76091] process > nullmod_skip_pca_grm      [100%] 1 of 1 ✔
[f1/ecf210] process > gwas_skip_pca_grm (chr_4) [  6%] 1 of 16, failed: 1
[-        ] process > caf_by_group_skip_pca_grm [  0%] 0 of 22
[-        ] process > merge_by_chr              -
[-        ] process > combine_results           -
[-        ] process > plot                      -
[-        ] process > annovar_input             -
[73/7ec72c] process > annovar_ref               [100%] 1 of 1 ✔
[-        ] process > annovar                   -
[-        ] process > add_annovar               -
[-        ] process > report                    -
Error executing process > 'gwas_skip_pca_grm (chr_3)'

Caused by:
  Process `gwas_skip_pca_grm (chr_3)` terminated with an error exit status (137)

Command executed:

  04_gwas.R chr_3.gds annot.rds nullmod.rds Score true chr_3.csv chr_3_gwas.log

Command exit status:
  137

Command output:
  [1] "Tue Sep 21 11:58:54 2021"

Command error:
  .command.sh: line 2:     7 Killed                  04_gwas.R chr_3.gds annot.rds nullmod.rds Score true chr_3.csv chr_3_gwas.log

**Comment by ZeyuanSong** [comment]
Hi, can you find the error message in the hidden dot file .nextflow.log? Is there any error message in the chr_3_gwas.log file?

**Comment by PavitaKae** [comment]
Hi, 
I try to run it again. it's happen with all Chr in process gwas_skip_pca_grm.
So,I check work folder, I not found input chr_xx.gds annot.rds nullmod.rds chr_xx.csv chr_3_gwas.log in work of gwas_skip_pca_grm.
But i found all input file in results/GDS.

I use N E X T F L O W  ~  version 21.04.3 it's a problem or not? what's version that you preferred?

**Comment by ZeyuanSong** [comment]
Hi, 
I run the test with Nextflow version 19.04.1. 
Are those files in results/GDS as small as empty (all same small sizes)? 
You may also try the other test example with 1KG data to see what happens.
